# auth-server-fix.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: litmus-auth-server
    app.kubernetes.io/instance: chaos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: litmus
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/version: 3.22.0
    helm.sh/chart: litmus-3.22.0
    litmuschaos.io/version: 3.22.0
  name: chaos-litmus-auth-server
  namespace: litmus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: litmus-auth-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: litmus-auth-server
        app.kubernetes.io/instance: chaos
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: litmus
        app.kubernetes.io/part-of: litmus
        app.kubernetes.io/version: 3.22.0
        helm.sh/chart: litmus-3.22.0
        litmuschaos.io/version: 3.22.0
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        # --- CORRECT CREDENTIALS FOR MAIN CONTAINER ---
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "litmus123"
        # -----------------------------------------------
        # Keep other env vars
        - name: LITMUS_GQL_GRPC_ENDPOINT
          value: chaos-litmus-server-service
        - name: LITMUS_GQL_GRPC_PORT
          value: "8000"
        - name: ENABLE_INTERNAL_TLS
          value: "false"
        - name: REST_PORT
          value: "3000"
        - name: GRPC_PORT
          value: "3030"
        - name: ALLOWED_ORIGINS
          value: .*
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
        envFrom: # Keep envFrom as fallback/other config
        - secretRef:
            name: chaos-litmus-admin-secret
        - configMapRef:
            name: chaos-litmus-admin-config
        image: litmuschaos.docker.scarf.sh/litmuschaos/litmusportal-auth-server:3.22.0
        imagePullPolicy: Always
        name: auth-server
        ports:
        - containerPort: 3000
          name: auth-server
          protocol: TCP
        - containerPort: 3030
          name: auth-rpc-server
          protocol: TCP
        resources:
          limits:
            cpu: 550m
            memory: 712Mi
          requests:
            cpu: 225m
            memory: 250Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 2000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        # Corrected command with -u ${DB_USER}
        - until  [[ $(mongosh -u ${DB_USER} -p ${DB_PASSWORD} ${DB_SERVER} --eval 'db.adminCommand("ping")' | grep 'ok' | wc -l) -eq 1 ]]; do sleep 5; echo 'Waiting for the MongoDB to be ready...'; done; echo 'Connection with MongoDB established'
        command:
        - /bin/bash
        - -c
        env:
        # --- CORRECT CREDENTIALS FOR INIT CONTAINER ---
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "litmus123"
        # -----------------------------------------------
        - name: DB_SERVER # Read correct DB_SERVER from ConfigMap
          valueFrom:
            configMapKeyRef:
              key: DB_SERVER
              name: chaos-litmus-admin-config
        image: litmuschaos.docker.scarf.sh/litmuschaos/mongo:6 # Image containing mongosh
        imagePullPolicy: Always
        name: wait-for-mongodb
        resources:
           limits:
             cpu: 250m
             memory: 512Mi
           requests:
             cpu: 25m
             memory: 150Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30